### PR TITLE
Adds footer to signed contract.

### PR DESCRIPTION
**Pull request by haarts**
boom

### CODE REVIEW

**Comment by lclc** [comment]
@haarts @OttoAllmendinger:  How did you proceed in the Go implementation?

Do we want to vote on this? This PR is getting dusty ;)

**Comment by OttoAllmendinger** [comment]
We have `ReadIncomplet()` and `WriteIncomplete()` on the go side already, so this is unnecessary.

If @haarts wants to make this work so that the function returns `false` if there is no signature section, we could spend a few more on this, but I'd rather just close it.

**Comment by benma** [comment]
I'd keep it open, the Go side is significantly messier than it needs to be.

**Comment by benma** [comment]
> <ttll> don't forget that skipping over lines also has consequences 
> <ttll> the displayed contract != what is hashed

With that, I see that this thing is too much effort. Closing.

**Pull request closed without merging**
