### PR TITLE
Dockerfile: create file for deb package

### PR DESCRIPTION
**Pull request by toxeus**
Usage:
    docker build -t opentxs-ci -f Dockerfiles/Dockerfile.CI .

Minimum Docker version required: 1.5

### CODE REVIEW

**Comment by toxeus** [comment]
@weissjeffm ping

**Comment by weissjeffm** [comment]
test this please (testing jenkins)

**Comment by mhamrle** [comment]
:+1: 

@monetas-ci re-test this please

**Comment by weissjeffm** [comment]
@toxeus what exactly does this do? It looks like I can create a docker image that contains the debian packages? But then I would also need a way to consume those packages (install them in another docker image?) I'm not sure how to use this.

**Pull request closed without merging**
