### PR TITLE
Remove PHP demo.

### LINKED ISSUE #52: PHP-Binding: Fix example
Or even better: write a native binding

### PR DESCRIPTION
**Pull request by haarts**
This demo is broken and deemed not worth the effort fixing. Removing the
examples leads to less confusion.
Closes #52.

### CODE REVIEW

**Comment by lclc** [comment]
@monetas-ci re-test this please (do I still have powers? I hope so)

Maybe we want to fully remove the PHP binding since nobody uses and maintains it?

**Comment by benma** [comment]
> 

:ok: :hammer:

**Comment by weissjeffm** [comment]
test this please

**Comment by weissjeffm** [comment]
test this please

**Comment by yamamushi** [comment]
This should be a pull request to fix the php demo, not to remove it.

**Pull request closed without merging**
