### PR TITLE
[Blockchain] Add support for XEC and XEC testnet3

### PR DESCRIPTION
**Pull request by TomaszAugustyn**

### CODE REVIEW

**Comment by justusranvier** [comment]
Adding the new functionality is fine, the coding style changes are not.

**Comment by TomaszAugustyn** [comment]
Do you mean removing { } in `case` statements?

**Comment by digital-michael** [comment]
Yes, I too am interested to get an exact, specific explanation of the complaint.

**Comment by digital-michael** [comment]
> Do you mean removing { } in `case` statements?
 Justus confirms: yes, restore the { and }.  Please expedite.

**Pull request merged**
