### PR TITLE
Rename account type simple -> user

### PR DESCRIPTION
**Pull request by mhamrle**
Renaming account type see https://github.com/monetas/design-docs/pull/3/files#diff-f5075794935bdcf71a480a6aa055ed93R40
This needs upgrade opentxs-tests.

### CODE REVIEW

**Comment by mhamrle** [comment]
tests PR https://github.com/monetas/opentxs-tests/pull/67

**Comment by toxeus** [comment]
:+1:

**Comment by haarts** [comment]
:+1:

**Comment by toxeus** [comment]
@monetas-ci test this please

**Pull request merged**
