### PR TITLE
Export currency decimal power and currency factor

### PR DESCRIPTION
**Pull request by mhamrle**

### CODE REVIEW

**Comment by toxeus** [comment]
@mhamrle can you please add to the commit message what this is good for?

**Comment by mhamrle** [comment]
@toxeus  Done. Android client needs to limit the amount of decimal digits a user can enter.

**Comment by toxeus** [comment]
@mhamrle thx! And why must they limit the amount of decimal digits?

**Comment by mhamrle** [comment]
@toxeus User experience. For example in contract BTC the smallest amount you can use is 0.001 BTC. If user does not know about this limitation he can set smaller amount and UI have to check it and inform user that he is not able to set so small amount (or amount with so many decimal digits). When you can check it during entering value you save lots of user stories and user displeasures.

**Comment by toxeus** [comment]
@mhamrle makes absolute sense. Thank you!

**Pull request merged**
