### PR TITLE
OT 118. Type erasure for client::ServerActions class.

### PR DESCRIPTION
**Pull request by bartalke**

### CODE REVIEW

**Comment by justusranvier** [comment]
Do not change the conventions for forward declarations. They should be consistent with the style used in other headers. See #1848.

**Comment by bartalke** [comment]
> The include-what-you-use tool will mostly put the forward declarations in the right format. You can use the iwyu-opentxs script to run that.
> 
> You should also set up the clang-format pre-commit hook from the readme.md

Ok, I added it and during push I got:

[08:26:32 PM] starting cppcheck
[08:26:32 PM] done cppcheck
include/opentxs/util/Container.hpp:20:0: error: failed to evaluate #if condition [preprocessorErrorDirective]
#if __has_include(<memory_resource>)
include/opentxs/util/Allocator.hpp:12:0: error: failed to evaluate #if condition [preprocessorErrorDirective]
#if __has_include(<memory_resource>)
src/otx/client/ServerAction.cpp:0:0: information: This file is not analyzed. Cppcheck failed to extract a valid configuration. Use -v for more details. [noValidConfiguration]
nofile:0:0: information: Unmatched suppression: nullPointer [unmatchedSuppression]
nofile:0:0: information: Unmatched suppression: ConfigurationNotChecked [unmatchedSuppression]
nofile:0:0: information: Unmatched suppression: passedByValue [unmatchedSuppression]
nofile:0:0: information: Unmatched suppression: unreadVariable [unmatchedSuppression]
==> cppcheck successfull

Did I do sth wrong that src/otx/client/ServerAction.cpp has not been analyzed ? I set the clang-format pre-commit/push hooks from the readme.md

**Comment by justusranvier** [comment]
The pre-push hook isn't working right now. Only use the pre-commit hook.

**Comment by bartalke** [comment]
> The pre-push hook isn't working right now. Only use the pre-commit hook.

Ok, done.

**Pull request merged**
