### PR TITLE
MEP-5 ISO timestamps

### PR DESCRIPTION
**Pull request by mhamrle**
based on #460

### CODE REVIEW

**Comment by mhamrle** [comment]
Fixed typos in comments, stop using  `OTTimeGetTimeFromSeconds`

**Comment by benma** [comment]
What about removing `[OTTimeGetTimeFromSeconds](https://github.com/Open-Transactions/opentxs/blob/develop/include/opentxs/core/util/Common.hpp#L221)` altogether?

**Comment by mhamrle** [comment]
@benma I agree but not in this PR.

**Comment by benma** [comment]
Ok. Please don't forget to update the [documention](https://github.com/monetas/protocol-docs/blob/master/content/DocumentTypes.md#L21).

**Comment by benma** [comment]
:+1: thanks @mhamrle!

**Pull request merged**
