### PR TITLE
ZeroMQ: enable Curve

### PR DESCRIPTION
**Pull request by toxeus**

### CODE REVIEW

**Comment by OttoAllmendinger** [comment]
nice :+1:

**Comment by OttoAllmendinger** [comment]
Good to see that the tests pass. 

Do you think we could do it minimally secure? Read the keys from the command line/config/environment?

**Comment by toxeus** [comment]
@OttoAllmendinger the correct way would be to fetch the keys from the notary provider contract. I don't think it's really worth the effort to bridge the current lack of the aforementioned mechanism with cmdline/config/environment because OTEnvelop "security" is still here. Keep in mind that we would have also to adapt the opentxs-tests and the Android client.

**Comment by OttoAllmendinger** [comment]
Oops, didn't notice that OTEnvelope is still in there. Nevermind then, we can figure out how to do it properly with the NotaryContract and leave it like that. I'll merge on Monday.

**Comment by toxeus** [comment]
@OttoAllmendinger please don't merge yet. The CI machine still needs some packages to be installed.

**Comment by toxeus** [comment]
@OttoAllmendinger you're free to merge

**Comment by OttoAllmendinger** [comment]
feels good man

**Pull request merged**
