### PR TITLE
Normalize the data that is signed/verified by trimming the spaces.

### PR DESCRIPTION
**Pull request by benma**
as part of the paylaod.

### CODE REVIEW

**Comment by toxeus** [comment]
@monetas-ci re-test this please

**Comment by weissjeffm** [comment]
This broke market tests. http://ci.opentransactions.org:8080/job/opentxs-PR-functional-test/9/

I'll look into why jenkins didn't mark it failed here on github.

**Comment by toxeus** [comment]
@monetas-ci re-test this please

**Comment by OttoAllmendinger** [comment]
One thing that we have to look out for is that we only do this where spaces really are unimportant, so probably all XML strings or armored strings that OT sign. But even though the the function is called `SignContract` and takes `string`, I can imagine where OT uses this to sign binary data (grep shows ~500 call sites). `Trim` would be a bad idea in those cases. 

So we should double-check this. or do `trim` only where we are absolutely sure that no binary stuff gets trimmed.

**Comment by benma** [comment]
@OttoAllmendinger 

You are probably right, and we should do the trimming in Contract.SignContract/VerifyContract. I'll look into it.

**Comment by benma** [comment]
retest this please

**Comment by benma** [comment]
retest this please

**Comment by benma** [comment]
retest this please

**Comment by toxeus** [comment]
:+1: great job!

**Pull request merged**
