### PR TITLE
Changed case in accordance to MEP 003.

### PR DESCRIPTION
**Pull request by haarts**
https://github.com/monetas/protocol-docs/blob/329bd174ce2c44e0bacfc261bbc45b7b0affa42b/content/mep/mep-003.md

good horse

### CODE REVIEW

**Comment by FellowTraveler** [comment]
It looks good to me. Does it pass all the unit tests?

**Comment by haarts** [comment]
It does.

**Comment by haarts** [comment]
And with the 'unit tests' you mean Jeff's tests?

**Comment by OttoAllmendinger** [comment]
LGTM

**Comment by benma** [comment]
test this please. If this doesn't work, @weissjeffm, please trigger tests and add me to the whitelist :)

**Comment by weissjeffm** [comment]
test this please.

I updated jenkins settings so now the entire monetas org should be whitelisted.

**Comment by toxeus** [comment]
@monetas-ci re-test this please

**Comment by toxeus** [comment]
Seems like only I have the super cow powers :v:

**Comment by mhamrle** [comment]
Please grep `decimal_power` in the code. There are some examples that contains `decimal_power`.
Otherwise :+1:

**Pull request merged**
