### PR TITLE
core: rename credentialList to credentialIDs

### PR DESCRIPTION
**Pull request by toxeus**

### CODE REVIEW

**Comment by lclc** [comment]
:+1: 
The changes necessary for the protocol look good. Maybe you also want to change the function names:
git grep CredentialList shows:

include/opentxs/core/Nym.hpp:    EXPORT bool SaveCredentialList();
include/opentxs/core/Nym.hpp:    EXPORT void SaveCredentialListToString(String& strOutput);
src/client/OTClient.cpp:        String strCredentialList;
src/client/OTClient.cpp:        ascArmor.GetString(strCredentialList);
src/client/OTClient.cpp:        if (strCredentialList.Exists()) {
src/client/OTClient.cpp:                    theTargetNym.LoadFromString(strCredentialList, &theMap)) {
src/client/OTClient.cpp:                    theNym.SaveCredentialList();
src/core/Contract.cpp:            String strCredentialList;
src/core/Contract.cpp:            credListArmor.GetString(strCredentialList);
src/core/Contract.cpp:            if (strCredentialList.Exists()) {
src/core/Contract.cpp:                    pNym->LoadFromString(strCredentialList, &credsMap)) {
src/core/Nym.cpp:    SaveCredentialList();
src/core/Nym.cpp:    SaveCredentialList();
src/core/Nym.cpp:    SaveCredentialList();
src/core/Nym.cpp:                    bSaved = SaveCredentialList();
src/core/Nym.cpp:void Nym::SaveCredentialListToString(String& strOutput)
src/core/Nym.cpp:bool Nym::SaveCredentialList()
src/core/Nym.cpp:    SaveCredentialListToString(strOutput);
src/server/UserCommandProcessor.cpp:        String strCredentialList(ascArmor);
src/server/UserCommandProcessor.cpp:        if (bHasCredentials && strCredentialList.Exists()) {
src/server/UserCommandProcessor.cpp:                pNym->LoadFromString(strCredentialList,

**Comment by haarts** [comment]
Excellent suggestion by @lclc

**Comment by toxeus** [comment]
@lclc thx. I only greped for the lowercase version :zap:

**Comment by mhamrle** [comment]
:+1:

**Comment by toxeus** [comment]
@monetas-ci re-test this please

**Pull request merged**
