### PR TITLE
OT_ME: merge called functions into caller

### PR DESCRIPTION
**Pull request by toxeus**

### CODE REVIEW

**Comment by mhamrle** [comment]
you can remove also QUERY_ASSET_TYPES

**Comment by toxeus** [comment]
fixed

**Comment by mhamrle** [comment]
:+1:  please squash and rebase

**Comment by toxeus** [comment]
@mhamrle squashed and rebased

**Comment by mhamrle** [comment]
@toxeus please rebase again, I merged #534

**Comment by toxeus** [comment]
@mhamrle rebased again

**Comment by mhamrle** [comment]
:+1:

**Pull request merged**
