### PR TITLE
getTransactionNumbersResponse: allocate a separate transaction number...

### PR DESCRIPTION
**Pull request by benma**
...for the receipt instead of reusing one of the numbers signed out
to the client.

Before, the first of the 100 numbers reserved for the client as reused.

See #464.

### CODE REVIEW

**Comment by toxeus** [comment]
@benma ping

**Comment by FellowTraveler** [comment]
Let me know if you want to sit with me in the office and go over this.

**Comment by benma** [comment]
Rebased. 

@toxeus: @FellowTraveler went over this with me, looks like everything is good. So it is ready to be merged (if the tests pass)

**Comment by benma** [comment]
retest this please

**Comment by toxeus** [comment]
@monetas-ci re-test this please

**Comment by toxeus** [comment]
@benma please rebase ;)

**Comment by weissjeffm** [comment]
retest this please (fixing jenkins)

**Comment by benma** [comment]
retest this please

**Comment by toxeus** [comment]
@monetas-ci re-test this please

**Comment by toxeus** [comment]
:+1:

**Pull request merged**
